### ISSUE TITLE
XMLHttpRequest error. No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by jpaulobneto** [wakatime/wakatime-mobile#2]
How to fix the following error?

![e9a9190c-2a81-11e5-9a4e-fcebf283a0ad](https://cloud.githubusercontent.com/assets/1436946/8740558/cb9bac94-2c21-11e5-9900-98ef5789ba76.png)

**Comment by DavidFrahm** [comment]
This blog post can help you setup Chrome to be able to run local without CORS issues: http://www.frahmbo.com/local-dev-chrome-browser/

**Comment by pritianka-zz** [comment]
Exciting to see the cool things you do on the mobile apps, Joao!  Thanks
for the mentoring, David!
ᐧ

Priyanka Sharma
Co-founder, WakaTime http://www.wakatime.com - Quantify your coding
www.twitter.com/pritianka
650-796-7125

**Comment by Borwe** [comment]
> This blog post can help you setup Chrome to be able to run local without CORS issues: http://www.frahmbo.com/local-dev-chrome-browser/

Link dead.
